server:
    port: 8091
    servlet:
       contextPath: /reasoner
security:
   basic:
      enabled: false
management:
   security:
      enabled: false
application:
   info:
      title: "k.LAB Reasoner API"
      description: "Porcaccio dio gesu"
      contactName: "Integrated Modelling Partnership"
      contactEmail: "info@integratedmodelling.org"